In [7]:
import numpy as np
import pandas as pd
import nltk 
from nltk.corpus import stopwords
import string

In [16]:
#load of data
from google.colab import files
uploaded=files.upload()

Saving spam_ham_dataset.csv to spam_ham_dataset.csv


In [41]:
df=pd.read_csv('spam_ham_dataset.csv')
df.head()

Unnamed: 0  ... label_num
0         605  ...         0
1        2349  ...         0
2        3624  ...         0
3        4685  ...         1
4        2030  ...         0

[5 rows x 4 columns]

In [18]:
#print the shape od data
df.shape

(5171, 4)

In [19]:
#get columns names
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [20]:
#check for duplicates and remove them
df.drop_duplicates(inplace=True)

In [21]:
#show the new shape
df.shape

(5171, 4)

In [22]:
#show the number of missing (NAN,NaN,nan) data for each column
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [23]:
#download the stopword package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [29]:
def process_text(text):
  #remove punctuation
  #remove stopwords
  #return a list of clean words
  nopunc=[char for char in text if char not in string.punctuation]
  nopunc=''.join(nopunc)

  clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  return clean_words

In [30]:
#show the tokenization(a list of token called lemmas)
df['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [33]:
#example 
message4='hello world hello hello world play'
message5= 'test test test test one hello'
print(message4)
print()

#convert the text to a matrix of token counts
from sklearn.feature_extraction.text import CountVectorizer
bow4=CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()

print(bow4.shape)


hello world hello hello world play

  (0, 0)	3
  (0, 4)	2
  (0, 2)	1
  (1, 0)	1
  (1, 3)	4
  (1, 1)	1

(2, 5)


In [35]:
 #convert a collection of text to a matriz of tokens
 from sklearn.feature_extraction.text import CountVectorizer
 message_bow=CountVectorizer(analyzer=process_text).fit_transform(df['text'])

In [43]:
#split the data into 80% training and 20%
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(message_bow,df['label_num'],test_size=0.20,random_state=0)

In [44]:
#get the shape of message_bow
message_bow.shape

(5171, 50381)

In [45]:
#create and train the naive bayes classifier
from sklearn.naive_bayes import MultinomialNB
classifier= MultinomialNB().fit(X_train,y_train)

In [47]:
#Print the predictions
print(classifier.predict(X_train))

#print the actual values
print(y_train.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 1 0 0]


In [50]:
 #evaluate the model on the training data set
 from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
 pred=classifier.predict(X_train)
 print(classification_report(y_train,pred))
 print()
 print('Confusion Matrix:\n',confusion_matrix(y_train,pred))
 print()
 print('Accuracy:',accuracy_score(y_train,pred))


              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2940
           1       0.98      0.97      0.98      1196

    accuracy                           0.99      4136
   macro avg       0.99      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136


Confusion Matrix:
 [[2918   22]
 [  30 1166]]

Accuracy: 0.9874274661508704


In [51]:
#Print the predictions
print(classifier.predict(X_test))

#print the actual values
print(y_test.values)

[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


In [54]:
#evaluate the model on the training data set
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score
pred=classifier.predict(X_test)
print(classification_report(y_test,pred))
print()
print('Confusion Matrix:\n',confusion_matrix(y_test,pred))
print()
print('Accuracy:',accuracy_score(y_test,pred))


              precision    recall  f1-score   support

           0       0.98      0.98      0.98       732
           1       0.95      0.96      0.96       303

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035


Confusion Matrix:
 [[718  14]
 [ 13 290]]

Accuracy: 0.9739130434782609
